package com.cleanarchitectkotlinflowhiltsimplestway.presentation.create.weather

import com.cleanarchitectkotlinflowhiltsimplestway.R
import com.cleanarchitectkotlinflowhiltsimplestway.presentation.base.BaseBottomSheetFragment

class WeatherSelectorDialog: BaseBottomSheetFragment(R.layout.dialog_select_weather) {


}