## 1
name: Build

## Actions that will be executed when you push code currently none
on:
  push:

## 2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v2
      # 2
      - name: Generate Release APK
        run: ./gradlew assembleRelease
      # 3
      - name: Build Signed APK
          uses: victorbnl/build-signed-apk@main
          id: sign_app
          with:
            keystore_b64: ${{ secrets.SIGNING_KEY }}
            keystore_password: ${{ secrets.KEY_STORE_PASSWORD }}
            key_alias: ${{ secrets.ALIAS }}
            key_password: ${{ secrets.KEY_PASSWORD }}
      # 4
      - uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      # 5
      - uses: actions/upload-artifact@main
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt