## 1
name: Build

## Actions that will be executed when you push code currently none
on:
  pull_request:
    branches:
      - develop

## 2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v2
      # 2
      - name: Generate Release APK
        run: ./gradlew assembleDebug
        id: build_app
      # 3
      - uses: actions/upload-artifact@v2
        with:
          name: Upload Debug App
          path: build/outputs/apk/develop/debug/app-develop-debug.apk
